### ISSUE TITLE
Dialog not showing in Ubuntu 14.04

### ISSUE THREAD

**Issue by caioss** [KabbAmine/vCoolor.vim#23]
Hi. I am not able to get vCooler to work on Ubuntu 14.04. I installed it with pathogen and it seems to be loaded (':echo g:vcoolor_loaded' prints 1). When I hit any of the shortcuts, nothing happens. I tried the following commands
let g:vcoolor_disable_mappings = 1
let g:vcoolor_map = '<leader>g'
, tried setting g:vcoolor_custom_picker to a zenity command that I tested in a terminal, but nothing happens.
As suggested in the youtube video, I ran it manually with ':VCoolor' and the dialog showed up. I then set the following map ':map <leader>g :VCoolor<cr>' and it worked.
The problem seems to be with the default mappings of vCoolor.
My Vim version is 7.4.

**Comment by KabbAmine** [comment]
With `g`, the color dialog shoud show up after some time, wait a little. This delay is due to the fact  that `g` is used by default by a lot of vim commands, so when used  vim is waiting for another key to be pressed.
The good way is to map it with another key(s) (e.g. `gc`, `gco`...).

For  the default map keys, as written in the [README](https://github.com/KabbAmine/vCoolor.vim#usage), if you're using Vim in a terminal the combination `Alt-c` may not work (The modifier keys there are handled differently). Let me know which mode are you using.

**Comment by KabbAmine** [comment]
I close the issue, feel free to open it again if needed.
